Update program.py
PaddleOCR/tools/program.py的第254行的变量名原为cur_metirc，需要修改为cur_metric，如果不修改在运行是，会提示
The variable name of line 254 can be changed to cur_ Metric. If you do not modify it, you will be prompted when it is running
"E:\XXX\PaddleOCR\tools\program.py", line 257, in train
    ['{}: {}'.format(k, v) for k, v in cur_metric.items()]))
NameError: name 'cur_metric' is not defined